version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      - dependency-name: "shadcn-nuxt"
        versions: ["^0.10.4"]
